---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgen-config
data:
  BACKEND_BASE_URL: http://backend:4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
    app.kubernetes.io/name: loadgen
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: loadgen
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: martinnirtl/demos.opentelemetry.loadgen:latest
          resources: {}
          envFrom:
            - configMapRef:
                name: loadgen-config
          env:
            - name: DT_INJECTION_RULES
              value: ::EXCLUDE:ALL,,
